language: objective-c
osx_image: xcode9.2

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild -workspace issueReader.xcworkspace -scheme issueReader -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO